import { getTemplate, type TemplateId } from './templates'

export type NoteData = {
  summary: string
  transcription: string
  title: string
  templateId: TemplateId | string
  participants: string[]
  createdAt: Date
}

export function formatNote(data: NoteData): string {
  const { summary, transcription, title, templateId, participants, createdAt } = data
  const template = getTemplate(templateId)
  const date = formatDate(createdAt)
  const time = formatTime(createdAt)
  const datetime = formatDatetime(createdAt)
  const participantsStr = participants.map(p => `"${p}"`).join(', ')

  return `---
title: ${title}
date: ${date}
time: ${time}
datetime: ${datetime}
template: ${template.name}
meeting_type: ${templateId}
participants: [${participantsStr}]
tags: [meeting, notes, auto-generated, ${templateId}]
---

# ${title}

**Date:** ${date}
**Time:** ${time}
**Template:** ${template.name}${participants.length > 0 ? `\n**Participants:** ${participants.join(', ')}` : ''}

---

## Summary

${summary}

---

## Full Transcription

<details>
<summary>Click to expand full transcription</summary>

\`\`\`
${transcription}
\`\`\`

</details>

---

*This meeting summary was automatically generated by Aura on ${datetime}.*
`
}

export function generateFilename(title: string, date: Date): string {
  const sanitized = title.replace(/[<>:"/\\|?*]/g, '').trim() || 'Meeting'
  const datePart = formatFilenameDate(date)
  return `${sanitized} - ${datePart}.md`
}

function formatDate(d: Date): string {
  const months = ['January','February','March','April','May','June','July','August','September','October','November','December']
  return `${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`
}

function formatTime(d: Date): string {
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`
}

function formatDatetime(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

function formatFilenameDate(d: Date): string {
  const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
  const months = ['January','February','March','April','May','June','July','August','September','October','November','December']
  return `${pad(d.getDate())} ${months[d.getMonth()]} ${d.getFullYear()}, ${days[d.getDay()]}`
}

function pad(n: number): string {
  return String(n).padStart(2, '0')
}
